plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.activityrecognition'
version = '1.0.0'

android {
  namespace "expo.modules.activityrecognition"
  defaultConfig {
    versionCode 1
    versionName "1.0.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation "com.google.android.gms:play-services-location:21.3.0"
}
